### ISSUE TITLE
Request for Usage Tutorial

### ISSUE THREAD

**Issue by CriandoValorTecnologia** [atteneder/DracoUnityDemo#3]
I'm having difficulties, to test the version within unity, have any video tutorial or some step by step to be able to use the program ? Thank you

**Comment by atteneder** [comment]
Hi,

Sorry to hear you're struggling to get it to work. I'll be thinking about a tutorial.

In the meantime, would you mind giving me more details what exactly you struggle with? Maybe I can help you and/or understand better what is not so clear to users.

Thanks!

**Comment by CriandoValorTecnologia** [comment]
I appreciate your help.
after downloading the folder of draco master , what do I need to do to make it work in unity ? I tried to put the draco unity folder in the unity proprio but i was not successful.

**Comment by atteneder** [comment]
If you check out this project (DracoUnityDemo), the package from the [DracoUnity](https://github.com/atteneder/DracoUnity) repository will automatically be installed (see Package Manager), so no need to copy anything. It will be installed, because it is listed in [Packages/manifest.json](https://github.com/atteneder/DracoUnityDemo/blob/121fd8327dc2b3968fbc725ffbfa52a57c7d04cf/Packages/manifest.json#L3).

Open the scene `Assets/Scenes/SampleScene`, enter playmode and press the space bar. A couple of 3D bunnies will be loaded from draco files.

hth

**Comment by atteneder** [comment]
Now there's also a minimalistic code example in the [DracoUnity README](https://github.com/atteneder/DracoUnity#using)
